name: Biweekly Puzzles

on:
  schedule:
    - cron: '0 12 * * 1,5'  # Executa todas segundas e sextas às 12:00 UTC
  workflow_dispatch:

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Clone completo do histórico

    - name: Pull latest changes
      run: git pull origin main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate puzzles
      run: python LOK_puzzles.py

    - name: Debug files
      run: |
        ls -la
        git status

    - name: Commit and push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md solucoes.md || echo "One or more files missing; skipping add"
        git commit -m "🔄 Biweekly update: $(date +'%d/%m/%Y')" || echo "Nothing to commit; skipping"
        git pull --rebase
        git push || echo "Push failed; may be up-to-date"
